Rpi virtuell v0.0.1
openeduhub/oeh-search-etl pull request #19
Opened 2021-05-27 16:17 UTC by Criamos

**Attention:** the "copyright"-metadata is a temporary solution for mapping licenses 
- **this should only go live after "rpi-virtuell" got back to us and clarified which licenses they actually use** (since they're only providing license descriptions, but don't mention any CC-like licenses / abbreviations anywhere on their site).

About the crawler:
- "rpi-virtuell" offers about **~10.900 items** via wp_json but doesn't provide that much useful metadata when using the API alone, therefore the "rpi_virtuell_spider"-crawler grabs metadata from both wp_json and the "material_review_url"-subpages and combines them into one lom_base item.
- The metadata-mapping might need some fine-tuning if categories seem off. rpi-virtuell's data model returns a lot of values that we can't 1:1 match

(As of 2021-05-27 this means each time the crawler is started it'll go through 109 API-calls within wp_json and ~10.900 URLs.)

2021-05-28 19:09 UTC, Criamos commented
rpi-virtuell got back to us with some clarifications regarding their license-descriptions:

rpi_virtuell_spider v0.0.2 includes these corrected copyright values

2021-06-01 10:07 UTC, sroertgen approved these changes
Sieht für mich alles schlüssig aus.
@torsten-simon wird wrsl noch anmerken, dass die GetId und GetHash Methoden der LomBase überschrieben werden sollten

2021-06-01 10:35 UTC, Criamos commented
> @torsten-simon wird wrsl noch anmerken, dass die GetId und GetHash Methoden der LomBase überschrieben werden sollten

Da bin ich aufgrund der Struktur der Metadaten ein bisschen gegen Wände gelaufen, denn die Problematik sah wie folgt aus:
- wenn ich die getHash und getID Methode überschrieben habe, dann wollten diese auch von der aktuellen wp_json/?page=<nummer> jeweils den Hash und die ID erzeugen, aber auf einer wp_json Seite liegen X Items (je nachdem wie viele Objekte die API returned, maximal jedoch 100 pro Seite), die die eigentlichen Material-Unterseiten mit der `material_review_url` in ihren Properties auflisten
- d.h. pro Seite hatte ich dann 100 Elemente, die sich erst mal die gleiche ID/Hash geholt hätten, obwohl sie allesamt zu unterschiedlichen Ziel-URLs führen würden
=> Meine Lösung war dann das Objekt manuell zusammenzubauen und hash/sourceID entsprechend mit den Werten aus der `material_review_url` zu hinterlegen, damit diese doppelten Zuweisungen gar nicht erst passieren können - zumindest laut debug meldungen beim Durchlauf wurden die bereits in edu-sharing eingetragenen Inhalte dann auch mit einer entsprechenden "skipping ..."-Nachricht erkannt und übersprungen

Mit etwas Zeit könnte ich das jedoch bei einem späteren Refactoring / Update des Crawlers nochmal versuchen, vielleicht lag das auch einfach nur an meiner ursprünglichen Implementation und der Reihenfolge, wie ich bei den ersten Versuchen die Metadaten extrahieren wollte.

2021-06-02 13:58 UTC, torsten-simon requested changes

2021-06-02 13:58 UTC, torsten-simon commented on requirements.txt
> +extruct
Please always use the exact versions, this will prevent future issues when installing requirements and frameworks might have changed

2021-06-02 14:06 UTC, torsten-simon approved these changes

2021-06-02 14:06 UTC, merged