sample_spider_alternative - first draft
openeduhub/oeh-search-etl pull request #30
Opened 2021-08-20 12:51 UTC by Criamos

Please take a look at the required/recommended/optional key-value pairs and let me know if there are mistakes.

2021-08-30 13:16 UTC, sroertgen requested changes
habe noch ein paar Kommentare eingefügt

2021-08-30 13:16 UTC, sroertgen commented on converter/spiders/sample_spider_alternative.py
> +        #  - oer                            recommended
wird das nicht abhängig von der Lizenz gesetzt?
also: ist es überhaupt nötig das zu setzen?

2021-08-30 13:16 UTC, sroertgen commented on converter/spiders/sample_spider_alternative.py
> +        #  - type               recommended
wird das Feld nicht hauptsächlich später edu-sharing intern verwendet? macht es sinn das hier zu erwähnen?
wenn ja, dürfen da alle Werte eingetragen werden?

bei ein paar Felder hier drunter ist es ähnlich, e.g. `uuid`, `collection`, `origin`, `ranking`, `fulltext` und `notes`.

Ich glaube einige werden ja automatisch noch befüllt (`fulltext`) und bei anderen kann man durch falsche werte vllt eher was kaputt machen, als dass es hilft.

2021-08-30 13:16 UTC, sroertgen commented on converter/spiders/sample_spider_alternative.py
> +        #  - format                         required
evtl hier noch einen kurzen Kommentar einfügen, was mit `format`` gemeint ist und einen Beispielwert einfügen

2021-08-30 13:16 UTC, sroertgen commented on converter/spiders/sample_spider_alternative.py
> +        #  - location                       required
hier das gleiche. Da der Wert required ist, kurzes Beispiel, was wir mit location meinen

2021-08-30 13:16 UTC, sroertgen commented on converter/spiders/sample_spider_alternative.py
> +        #  - role                           recommended
evtl Hinweis auf verfügbare roles

2021-08-30 13:16 UTC, sroertgen commented on converter/spiders/sample_spider_alternative.py
> +        #  - description                    recommended
da wir description ja auch schon oben haben. Dieses meint als Unterpunkt von `Educational`: "Comments on how this learning object is to be used."

2021-08-30 13:16 UTC, sroertgen commented on converter/spiders/sample_spider_alternative.py
> +        #  - discipline                     recommended
hier und folgend könnten wir noch die Links zu den jeweiligen Wertelisten hinterlegen. Und vllt unten ein Beispiel, wie die Werte dann hinzugefügt werden. (btw könnte man eigtl auch die ID statt den String nehmen? Wenn sich das prefLabel bei den Vokabularen mal ändern sollte, knallen ja die ganzen Crawler..)

2021-08-30 13:16 UTC, sroertgen commented on converter/spiders/sample_spider_alternative.py
> +        #  - discipline                     recommended
bzw altLabels werden ja auch durchsucht. Aber falls ein Label mal ganz rausfliegt ( was es wahrscheinlich nicht tut) würde es knallen

2021-08-31 15:20 UTC, Criamos commented
- Die gewünschten Änderungen sind jetzt drin
- den commit mit der requirements.txt (update auf playwright v1.14) hab ich gedropped, sodass der PR nur noch die sample_spider_alternative.py enthält

Wenn das so passt, würd ich den Draft dann als nächstes zum PR umwandeln :)

2021-09-01 12:55 UTC, sroertgen approved these changes

2021-09-01 13:03 UTC, merged